Repository yeongkkeul/yeongkkuel-server, pull requests merged in 2025-02, with the labels that each got.

#80 FIX,FEAT: 카카오 인가코드 방식이 아닌 AccessToken 방식으로 로그인 ,SpringBatch 채팅방 내 사용자 점수 갱신(테스트 진행중)
  build.gradle
  src/main/java/com/umc/yeongkkeul/batch/BatchScheduler.java
  src/main/java/com/umc/yeongkkeul/batch/UserScoreBatchConfig.java
  src/main/java/com/umc/yeongkkeul/domain/mapping/ChatRoomMembership.java
  src/main/java/com/umc/yeongkkeul/repository/ChatRoomMembershipRepository.java
  src/main/java/com/umc/yeongkkeul/web/controller/UserController.java
Labels: feature, fix

#87 fix: s3 upload manager의 MIME기반 타입 메타데이터 추가
  src/main/java/com/umc/yeongkkeul/aws/s3/AmazonS3Manager.java
Labels: bug

#97 feat: 카테고리 삭제시, 종속된 지출 내역을 임시 카테고리에 보존하도록 로직변경
  src/main/java/com/umc/yeongkkeul/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/yeongkkeul/repository/CategoryRepository.java
  src/main/java/com/umc/yeongkkeul/service/CategoryCommandServiceImpl.java
  src/main/java/com/umc/yeongkkeul/service/ExpenseCommandServiceImpl.java
Labels: feature

#90 [FEAT] 채팅방 2 3순위 api
  src/main/java/com/umc/yeongkkeul/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/yeongkkeul/apiPayload/exception/handler/ChatRoomMembershipHandler.java
  src/main/java/com/umc/yeongkkeul/domain/ChatRoom.java
  src/main/java/com/umc/yeongkkeul/repository/ChatRoomMembershipRepository.java
  src/main/java/com/umc/yeongkkeul/repository/ChatRoomRepository.java
  src/main/java/com/umc/yeongkkeul/service/ChatService.java
  src/main/java/com/umc/yeongkkeul/web/controller/ChatAPIController.java
  src/main/java/com/umc/yeongkkeul/web/controller/ChatController.java
  src/main/java/com/umc/yeongkkeul/web/dto/chat/PublicChatRoomsDetailResponseDto.java
Labels: feature

#107 fix: 지출 목록 조회 시 카테고리 id도 반환하도록 수정
  src/main/java/com/umc/yeongkkeul/converter/CategoryConverter.java
  src/main/java/com/umc/yeongkkeul/web/dto/CategoryResponseDTO.java
Labels: fix

#110 feat: channelinterceptor를 기반한 socket의 연결 상태 추적 로직 추가
  src/main/java/com/umc/yeongkkeul/config/WebSocketBrokerConfig.java
  src/main/java/com/umc/yeongkkeul/service/ChatService.java
  src/main/java/com/umc/yeongkkeul/socket/SocketConnectionTracker.java
  src/main/java/com/umc/yeongkkeul/socket/SocketSessionInterceptor.java
Labels: feature

#114 [FIX] 채팅방 둘러보기 정렬 수정
  src/main/java/com/umc/yeongkkeul/repository/ChatRoomRepository.java
  src/main/java/com/umc/yeongkkeul/service/ChatService.java
  src/main/java/com/umc/yeongkkeul/web/controller/ChatAPIController.java
Labels: fix

#121 feat: 지출내역 생성시, 영수증 채팅방마다 stream으로 전송
  src/main/java/com/umc/yeongkkeul/web/controller/ExpenseController.java
Labels: feature

#129 refactor: 영수증 전송 로직 서비스로 분리
  src/main/java/com/umc/yeongkkeul/service/ChatService.java
  src/main/java/com/umc/yeongkkeul/web/controller/ExpenseController.java
Labels: refactor

#134 Fix: 테스트 완료로 인한 정상화
  src/main/java/com/umc/yeongkkeul/security/TokenProvider.java
Labels: fix

#137 feat: 채팅방 이미지 업로드 이후, 채팅방 전송로직 추가
  src/main/java/com/umc/yeongkkeul/service/ChatService.java
  src/main/java/com/umc/yeongkkeul/web/controller/ChatAPIController.java
Labels: feature

#141 feat: 로그인시 해당 유저의 userId 추가로 리턴하도록 로직 변경
  src/main/java/com/umc/yeongkkeul/repository/UserRepository.java
  src/main/java/com/umc/yeongkkeul/service/GoogleLoginService.java
  src/main/java/com/umc/yeongkkeul/service/KakaoLoginService.java
  src/main/java/com/umc/yeongkkeul/web/dto/SocialInfoResponseDto.java
Labels: bug, feature

#144 [FEATURE] 홈 - 전날 획득한 리워드 조회 api 구현
  src/main/java/com/umc/yeongkkeul/repository/RewardRepository.java
  src/main/java/com/umc/yeongkkeul/service/HomeQueryService.java
  src/main/java/com/umc/yeongkkeul/service/HomeQueryServiceImpl.java
  src/main/java/com/umc/yeongkkeul/web/controller/HomeController.java
  src/main/java/com/umc/yeongkkeul/web/dto/HomeResponseDTO.java
Labels: feature

#157 feat: 채팅방 생성 시 url이 아닌 이미지 입력하도록 변경
  src/main/java/com/umc/yeongkkeul/converter/ChatRoomConverter.java
  src/main/java/com/umc/yeongkkeul/service/ChatService.java
  src/main/java/com/umc/yeongkkeul/web/controller/ChatAPIController.java
  src/main/java/com/umc/yeongkkeul/web/dto/chat/ChatRoomDetailRequestDto.java
Labels: feature

#164 fix: 카테고리가 지니고 있는 expenseList 필드를 빌더에서 초기화 보장하도록 Default 지정
  src/main/java/com/umc/yeongkkeul/domain/Category.java
Labels: bug

#171 [FIX] 채팅방 생성 초기값 변경
  src/main/java/com/umc/yeongkkeul/converter/ChatRoomConverter.java
  src/main/java/com/umc/yeongkkeul/service/ChatService.java
  src/main/java/com/umc/yeongkkeul/web/controller/ChatAPIController.java
Labels: fix

#173 feat: 카테고리 생성시, 최대개수 반영
  src/main/java/com/umc/yeongkkeul/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/yeongkkeul/repository/CategoryRepository.java
  src/main/java/com/umc/yeongkkeul/service/CategoryCommandServiceImpl.java
Labels: feature

#175 feat: 카테고리 n일 연속 무지출 달성 리워드 지급
  src/main/java/com/umc/yeongkkeul/domain/Category.java
  src/main/java/com/umc/yeongkkeul/domain/User.java
  src/main/java/com/umc/yeongkkeul/repository/ExpenseRepository.java
  src/main/java/com/umc/yeongkkeul/service/ExpenseCommandServiceImpl.java
Labels: enhancement, feature

#177 fix: 카테고리 각각 적용하도록 로직 변경
  src/main/java/com/umc/yeongkkeul/repository/ExpenseRepository.java
  src/main/java/com/umc/yeongkkeul/service/ExpenseCommandServiceImpl.java
Labels: bug

#179 fix: 이미지 업로드 reqBody 대신 reqParam으로 변경
  src/main/java/com/umc/yeongkkeul/web/controller/ChatAPIController.java
Labels: bug

#183 fix: 채팅방 메시지 id값 불일치 현상 직렬화 문제 해결
  src/main/java/com/umc/yeongkkeul/service/ChatService.java
  src/main/java/com/umc/yeongkkeul/web/dto/chat/MessageDto.java
Labels: bug

#185 [BUG] 채팅방 입장/퇴장 버그 수정
  src/main/java/com/umc/yeongkkeul/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/yeongkkeul/service/ChatService.java
  src/main/java/com/umc/yeongkkeul/web/controller/ChatController.java
Labels: bug

#105 [FEAT] 채팅 읽음 상태 처리 첫 번째 방법
  src/main/java/com/umc/yeongkkeul/repository/ChatRoomMembershipRepository.java
  src/main/java/com/umc/yeongkkeul/service/ChatService.java
  src/main/java/com/umc/yeongkkeul/web/controller/ChatController.java
  src/main/java/com/umc/yeongkkeul/web/dto/chat/MessageDto.java
  src/main/java/com/umc/yeongkkeul/web/dto/chat/ReadMessageRequestDto.java
  src/main/java/com/umc/yeongkkeul/web/dto/chat/ReadMessageResponseDto.java
Labels: feature

#187 [FIX] 동기화 로직 변경
  src/main/java/com/umc/yeongkkeul/service/ChatService.java
  src/main/java/com/umc/yeongkkeul/web/controller/ChatAPIController.java
  src/main/java/com/umc/yeongkkeul/web/dto/chat/ChatSettingResponseDto.java
Labels: fix
