Repository yeongkkeul/yeongkkuel-server, pull requests merged in 2025-01, with the labels that each got.

#13 [FEAT] 상점 아이템, 아이템 구매 이력 Entity 추가
  src/main/java/com/umc/yeongkkeul/domain/Item.java
  src/main/java/com/umc/yeongkkeul/domain/Notification.java
  src/main/java/com/umc/yeongkkeul/domain/enums/ItemType.java
  src/main/java/com/umc/yeongkkeul/domain/enums/NotificationType.java
  src/main/java/com/umc/yeongkkeul/domain/mapping/Purchase.java
Labels: feature

#23 16 feature category 관련 api 구현
  build.gradle
  src/main/java/com/umc/yeongkkeul/apiPayload/ApiResponse.java
  src/main/java/com/umc/yeongkkeul/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/yeongkkeul/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/umc/yeongkkeul/apiPayload/exception/handler/.gitkeep
  src/main/java/com/umc/yeongkkeul/apiPayload/exception/handler/CategoryHandler.java
  src/main/java/com/umc/yeongkkeul/apiPayload/exception/handler/UserHandler.java
  src/main/java/com/umc/yeongkkeul/config/TestDataInitializer.java
  src/main/java/com/umc/yeongkkeul/converter/.gitkeep
  src/main/java/com/umc/yeongkkeul/converter/CategoryConverter.java
  src/main/java/com/umc/yeongkkeul/domain/Category.java
  src/main/java/com/umc/yeongkkeul/domain/User.java
  src/main/java/com/umc/yeongkkeul/domain/enums/Color.java
  src/main/java/com/umc/yeongkkeul/repository/.gitkeep
  src/main/java/com/umc/yeongkkeul/repository/CategoryRepository.java
  src/main/java/com/umc/yeongkkeul/repository/UserRepository.java
  src/main/java/com/umc/yeongkkeul/service/.gitkeep
  src/main/java/com/umc/yeongkkeul/service/CategoryCommandService.java
  src/main/java/com/umc/yeongkkeul/service/CategoryCommandServiceImpl.java
  src/main/java/com/umc/yeongkkeul/service/CategoryQueryService.java
  src/main/java/com/umc/yeongkkeul/service/CategoryQueryServiceImpl.java
  src/main/java/com/umc/yeongkkeul/service/UserCommandService.java
  src/main/java/com/umc/yeongkkeul/service/UserCommandServiceImpl.java
  src/main/java/com/umc/yeongkkeul/web/controller/.gitkeep
  src/main/java/com/umc/yeongkkeul/web/controller/CategoryController.java
  src/main/java/com/umc/yeongkkeul/web/controller/UserController.java
  src/main/java/com/umc/yeongkkeul/web/dto/.gitkeep
  src/main/java/com/umc/yeongkkeul/web/dto/CategoryRequestDTO.java
  src/main/java/com/umc/yeongkkeul/web/dto/CategoryResponseDTO.java
Labels: feature

#27 feat: 홈 관련 api 구현 #18
  build.gradle
  src/main/java/com/umc/yeongkkeul/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/yeongkkeul/apiPayload/exception/handler/ExpenseHandler.java
  src/main/java/com/umc/yeongkkeul/apiPayload/exception/handler/PurchaseHandler.java
  src/main/java/com/umc/yeongkkeul/converter/CategoryConverter.java
  src/main/java/com/umc/yeongkkeul/converter/ExpenseConverter.java
  src/main/java/com/umc/yeongkkeul/converter/PurchaseConverter.java
  src/main/java/com/umc/yeongkkeul/domain/Expense.java
  src/main/java/com/umc/yeongkkeul/domain/Item.java
  src/main/java/com/umc/yeongkkeul/domain/User.java
  src/main/java/com/umc/yeongkkeul/domain/enums/NotificationType.java
  src/main/java/com/umc/yeongkkeul/domain/mapping/Purchase.java
  src/main/java/com/umc/yeongkkeul/repository/CategoryRepository.java
  src/main/java/com/umc/yeongkkeul/repository/ExpenseRepository.java
  src/main/java/com/umc/yeongkkeul/repository/ItemRepository.java
  src/main/java/com/umc/yeongkkeul/repository/PurchaseRepository.java
  src/main/java/com/umc/yeongkkeul/service/ExpenseCommandService.java
  src/main/java/com/umc/yeongkkeul/service/ExpenseCommandServiceImpl.java
  src/main/java/com/umc/yeongkkeul/service/HomeQueryService.java
  src/main/java/com/umc/yeongkkeul/service/HomeQueryServiceImpl.java
  src/main/java/com/umc/yeongkkeul/web/controller/ExpenseController.java
  src/main/java/com/umc/yeongkkeul/web/controller/HomeController.java
  src/main/java/com/umc/yeongkkeul/web/dto/CategoryResponseDTO.java
  src/main/java/com/umc/yeongkkeul/web/dto/ExpenseRequestDTO.java
  src/main/java/com/umc/yeongkkeul/web/dto/ExpenseResponseDTO.java
  src/main/java/com/umc/yeongkkeul/web/dto/HomeResponseDTO.java
  src/main/java/com/umc/yeongkkeul/web/dto/PurchaseResponseDTO.java
  src/main/resources/application.yml
Labels: feature

#30 [FIX] Message Entity와 관련 객체 그래프 탐색 코드 제거
  src/main/java/com/umc/yeongkkeul/domain/ChatRoom.java
  src/main/java/com/umc/yeongkkeul/domain/Message.java
  src/main/java/com/umc/yeongkkeul/domain/User.java
Labels: fix

#39 feat: 카테고리 관련 api 수정 및 Swagger 명세 추가 #32
  src/main/java/com/umc/yeongkkeul/web/controller/CategoryController.java
Labels: documentation, feature

#45 FEAT: "Google 로그인 구현"
  build.gradle
  src/main/java/com/umc/yeongkkeul/repository/UserRepository.java
  src/main/java/com/umc/yeongkkeul/repository/UserTermsRepository.java
  src/main/java/com/umc/yeongkkeul/service/GoogleLoginService.java
  src/main/java/com/umc/yeongkkeul/service/KakaoLoginService.java
  src/main/java/com/umc/yeongkkeul/web/controller/UserController.java
  src/main/java/com/umc/yeongkkeul/web/dto/GoogleInfoResponseDto.java
  src/main/java/com/umc/yeongkkeul/web/dto/GoogleTokenDto.java
  src/main/java/com/umc/yeongkkeul/web/dto/GoogleTokenResponseDto.java
  src/main/java/com/umc/yeongkkeul/web/dto/SocialInfoResponseDto.java
Labels: feature

#53 FEAT: 아이템 별 상점 조회, 스킨 확인, 스킨 구매, 스킨 착용(저장) api 구현
  src/main/java/com/umc/yeongkkeul/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/yeongkkeul/domain/Item.java
  src/main/java/com/umc/yeongkkeul/domain/enums/ItemType.java
  src/main/java/com/umc/yeongkkeul/domain/mapping/Purchase.java
  src/main/java/com/umc/yeongkkeul/repository/ItemRepository.java
  src/main/java/com/umc/yeongkkeul/repository/PurchaseRepository.java
  src/main/java/com/umc/yeongkkeul/service/StoreService.java
  src/main/java/com/umc/yeongkkeul/web/controller/StoreController.java
  src/main/java/com/umc/yeongkkeul/web/dto/PurchaseRequestDto.java
  src/main/java/com/umc/yeongkkeul/web/dto/StoreResponseDto.java
Labels: feature

#56 [FEAT] 알림 crud 구현
  src/main/java/com/umc/yeongkkeul/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/yeongkkeul/apiPayload/exception/handler/NotificationReadHandler.java
  src/main/java/com/umc/yeongkkeul/config/SecurityConfig.java
  src/main/java/com/umc/yeongkkeul/converter/NotificationConverter.java
  src/main/java/com/umc/yeongkkeul/domain/Notification.java
  src/main/java/com/umc/yeongkkeul/domain/enums/NotificationType.java
  src/main/java/com/umc/yeongkkeul/domain/mapping/NotificationRead.java
  src/main/java/com/umc/yeongkkeul/repository/NotificationReadRepository.java
  src/main/java/com/umc/yeongkkeul/repository/NotificationRepository.java
  src/main/java/com/umc/yeongkkeul/service/NotificationService.java
  src/main/java/com/umc/yeongkkeul/web/controller/NotificationController.java
  src/main/java/com/umc/yeongkkeul/web/dto/NotificationAgreedRequestDto.java
  src/main/java/com/umc/yeongkkeul/web/dto/NotificationDetailRequestDto.java
  src/main/java/com/umc/yeongkkeul/web/dto/NotificationDetailsResponseDto.java
Labels: feature
